/* RaiseComplaintModal.tsx — FE-07
 * SRS §5: "Raise Complaint → Assign → Corrective Action → Status → Remarks → Close".
 * The raise step is deliberately short (title, category, priority, description)
 * because the SRS asks for this module to be "simple but complete".
 *
 * The route validator requires categoryId, priorityKey and title, so those are
 * validated client-side too. `clientRequestId` is generated by the hook. */

import { useState } from 'react';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { FormField } from '@/components/ui/FormField';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import { Select } from '@/components/ui/Select';
import { Alert } from '@/components/ui/Alert';
import { useCreateComplaint } from '../hooks/useComplaints';
import {
  useComplaintCategoryOptions,
  useComplaintPriorityOptions,
} from '../hooks/useComplaintLookups';
import { useFlatOptions } from '@/features/members/hooks/useFlatOptions';
import { LookupSelect } from '@/components/data/LookupSelect';
import type { Complaint } from '@/types/domain';

interface RaiseComplaintModalProps {
  open: boolean;
  onClose: () => void;
  /** Called with the created complaint so the caller can navigate to it. */
  onCreated?: (complaint: Complaint) => void;
}

export function RaiseComplaintModal({ open, onClose, onCreated }: RaiseComplaintModalProps) {
  const { creating, error, create } = useCreateComplaint();
  const categories = useComplaintCategoryOptions();
  const priorities = useComplaintPriorityOptions();
  const flats = useFlatOptions();

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [categoryId, setCategoryId] = useState('');
  const [priorityKey, setPriorityKey] = useState('');
  const [flatId, setFlatId] = useState('');
  const [touched, setTouched] = useState(false);

  const titleError = touched && !title.trim() ? 'Title is required' : undefined;
  const categoryError = touched && !categoryId ? 'Category is required' : undefined;
  const priorityError = touched && !priorityKey ? 'Priority is required' : undefined;

  const resetFields = () => {
    setTitle('');
    setDescription('');
    setCategoryId('');
    setPriorityKey('');
    setFlatId('');
    setTouched(false);
  };

  const submit = async () => {
    setTouched(true);
    if (!title.trim() || !categoryId || !priorityKey) return;

    const created = await create({
      title: title.trim(),
      description: description.trim() || undefined,
      categoryId,
      priorityKey,
      flatId: flatId || undefined,
      source: 'WEB',
    });

    if (created) {
      resetFields();
      onCreated?.(created);
      onClose();
    }
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Raise a complaint"
      footer={
        <>
          <Button variant="ghost" onClick={onClose} disabled={creating}>
            Cancel
          </Button>
          <Button onClick={() => void submit()} loading={creating}>
            Raise complaint
          </Button>
        </>
      }
    >
      {error ? <Alert variant="danger">{error}</Alert> : null}

      <FormField label="Title" required error={titleError}>
        <Input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="Short summary of the issue"
          maxLength={120}
        />
      </FormField>

      <div className="hs-grid hs-grid-cols-2" style={{ gap: 'var(--space-4)' }}>
        <FormField label="Category" required error={categoryError}>
          <Select
            options={categories.options}
            value={categoryId}
            onChange={(e) => setCategoryId(e.target.value)}
            placeholder={categories.loading ? 'Loading...' : 'Select a category'}
            disabled={categories.loading}
          />
        </FormField>

        <FormField label="Priority" required error={priorityError}>
          <Select
            options={priorities.options}
            value={priorityKey}
            onChange={(e) => setPriorityKey(e.target.value)}
            placeholder={priorities.loading ? 'Loading...' : 'Select a priority'}
            disabled={priorities.loading}
          />
        </FormField>
      </div>

      <FormField label="Flat" hint="Optional — leave blank for a common-area issue">
        <LookupSelect
          options={flats.options}
          value={flatId}
          onChange={setFlatId}
          loading={flats.loading}
          onSearch={flats.searchFlats}
          placeholder="Select a flat"
          searchPlaceholder="Search by flat number..."
        />
      </FormField>

      <FormField label="Description" hint="What is the problem, and where exactly?">
        <Textarea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={4}
          maxLength={2000}
        />
      </FormField>
    </Modal>
  );
}
